//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Highscore { get; set; }
        public int Tens { get; set; }
        public int Hundreds { get; set; }
        public int Thousands { get; set; }
        public int TenThousands { get; set; }
        public int HundredThousands { get; set; }
        public int Millions { get; set; }
        public string Salt { get; set; }
    }
}
